object Versions {
    const val compose = "1.1.1"
    const val composeCompiler = "1.2.0"
    const val hiltPlugin = "2.42"
    const val jUnit = "4.13.2"
    const val jUnitExt = "1.1.3"
    const val espresso = "3.4.0"
    const val coreKtx = "1.8.0"
    const val hilt = "2.42"
    const val hiltCompiler = "1.0.0"
    const val retrofit = "2.9.0"
    const val okHttp = "4.10.0"
    const val coroutines = "1.6.3"
    const val jvmInject = "1"
    const val room = "2.4.2"
    const val lifecycleRuntime = "2.4.1"
    const val composeActivity = "1.3.1"
}